### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by LukaAvbreht** [zigazupancic/merelles#20]
v primeru ko ima eden izmed igralcev le se 3 figure (in lahko leti), ter drugi igralec zablokira prvega igralca tako da ce nebi mogel leteti nebi imel veljavnih potez, se igra konca, kljub temu da navidezno zablokirani igralec ni zablokiran
![mereles bug](https://cloud.githubusercontent.com/assets/12804493/13723595/1504e314-e86a-11e5-9f5e-657eac72e926.PNG)

**Comment by zigazupancic** [comment]
Popravljeno z 1d4c3cd
